### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by joshbali** [javiervidrua/autoconfiguredns#1]
The script installs an open recursive DNS resolver which is a major security issue as it can be used for DNS amplification attacks.

The "named.conf.options" file should contain:

allow-query { none; };

but it contains:

allow-query { any; }; 

or, even better, keep the bind9 default zone settings .
At least you should mention this in the readme.

Cheers

**Comment by javiervidrua** [comment]
If you change the "named.conf.options" file from this:

allow-query { any; };

To this:

allow-query { none; };

The DNS stops working because it does not accept queries. Like no queries.
So it should contain: 

allow-query { any; };

Cheers

**Comment by joshbali** [comment]
Yes. Correct. This has to be changed to any trusted slave/secondary DNS server IP to accept queries from. But you can't create an open resolver from the start. This should be at least reflected in the Readme to make it clear that this is an insecure setup which has to be adjusted. Anyway. Thank you for the script. It saves some time.

**Comment by javiervidrua** [comment]
You're right. This should be mentioned on the readme, and will be.
Thank you for taking the time to use the script, test it, and give me some good feedback!

Cheers!
