### ISSUE TITLE
Reverse zone file reference

### ISSUE THREAD

**Issue by joshbali** [javiervidrua/autoconfiguredns#2]
The script creates a reverse zone file with the domain name but refers to a reverse zone file named with the IP in named.conf.local causing the bind9 conf check to fail.

**Comment by javiervidrua** [comment]
Made a clean install of Debian 10 Buster.
Ran the script.
Ran: 
  "named-checkconf /etc/bind/named.conf"
  "named-checkconf /etc/bind/named.conf.local"

Both commands return no output so the files have no errors.
Maybe you tried to use the script on a system that already has bind9 installed and that's the reason why it failed the conf check.
